name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest_with_default_input_argument
        uses: yoyonel/retrieve-labels-pr-action@master
      - name: Check outputs
        run: |
          test "${{ steps.selftest_with_default_input_argument.outputs.myOutput }}" == "Hello world"
      - name: Self test
        id: selftest_with_arg
        uses: yoyonel/retrieve-labels-pr-action@master
        with:
          myInput: test
      - name: Check outputs
        run: |
          test "${{ steps.selftest_with_arg.outputs.myOutput }}" == "Hello test"
